heading = []
username = input('Введите ваше имя: ')
title1 = heading.append(input('Введите заголовок заметки №1 : '))
title2 = heading.append(input('Введите заголовок заметки №2 : '))
title3 = heading.append(input('Введите заголовок заметки №3 : '))
content = input('Введите описание заметки: ')
status = input('Введите статус заметки: ')
created_date = input('Введите дату создания заметки в формате дд.мм.гггг: ')
issue_date = input('Введите дату истечения заметки в формате дд.мм.гггг: ')

print('Имя пользователя: ', username)
print('Заголовки заметок: ', heading)
print('Описание заметки: ', content)
print('Статус заметки: ', status)
print('Дата создания заметки: ', created_date)
print('Дата истечения заметки: ', issue_date)
